#LEX = flex -I
#YACC = bison

CC=cc -DYYDEBUG=1
ch3-04: y.tab.o lex.yy.o ch3.o
	$(CC) -o ch3-04 $^ -lm

lex.yy.o : lex.yy.c y.tab.h
y.tab.o: y.tab.c y.tab.h ch3hdr.h
ch3.o: ch3.c ch3hdr.h

y.tab.c: ch3-04.y
	yacc -d $*

lex.yy.c: ch3-04.l
	lex $*
